export enum PreferenceType {
    FICTION = 'fiction',
    NON_FICTION = 'non-fiction',
    FANTASY = 'fantasy',
    MYSTERY = 'mystery',
    ROMANCE = 'romance',
    SCIENCE_FICTION = 'science-fiction',
    BIOGRAPHY = 'biography',
    SELF_HELP = 'self-help',
    HISTORY = 'history',
    THRILLER = 'thriller',
    CHILDREN = 'children',
    YOUNG_ADULT = 'young-adult',
    HORROR = 'horror',
    CLASSICS = 'classics',
    POETRY = 'poetry',
    ADVENTURE = 'adventure',
    PHILOSOPHY = 'philosophy',
    EDUCATION = 'education',
    COMICS = 'comics',
    SPIRITUALITY = 'spirituality'
}
